import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components";
import "./globals.css";
import { AuthProvider } from "@/providers/auth";
import { ModalProvider } from "@/context/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistema de controle",
  description: "Generated by create Julio Freitas",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ModalProvider>
            <Header />
            {children}
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
